### PR TITLE
Fix RGB24/ARGB32 conversions (Fixes #163)

### LINKED ISSUE #163: Problems with RGB24/ARGB32 conversions
PR #158 revealed the following conversion problems:
```julia
julia> convert(AbstractARGB{RGB,N0f8}, RGB24(), 0.2)
ERROR: No conversion of (RGB24(0.0N0f8,0.0N0f8,0.0N0f8),alpha=0.2) to ARGB{Normed{UInt8,8}} with consistency-types RGB and RGB24 has been defined

julia> convert(ARGB32, RGB(), 0.2)
ERROR: No conversion of (RGB{N0f8}(0.0,0.0,0.0),alpha=0.2) to ARGB32 with consistency-types RGB24 and RGB has been defined

julia> convert(ARGB, RGB24(), 0.2)
ERROR: No conversion of (RGB24(0.0N0f8,0.0N0f8,0.0N0f8),alpha=0.2) to ARGB{Normed{UInt8,8}} with consistency-types RGB and RGB24 has been defined
```
PR #161 is going to fix some conversion problems, but the problems above may be not fixed.
These conversions are (re-)implemented in Colors.jl. I want to clarify the division of functionality with ColorTypes.jl in the next version of Colors.jl.

There are two minor problems:
```julia
julia> real(Gray(0.6))
0.6

julia> real(Gray24(0.6))
ERROR: MethodError: no method matching real(::Gray24)
```
```julia
julia> convert(AGray32, 0.6, 0.2)
AGray32{N0f8}(0.6,0.2)

julia> convert(ARGB32, 0.6, 0.2)
ERROR: MethodError: no method matching convert(::Type{ARGB32}, ::Float64, ::Float64)
```

I'm ready to fix this issue. I will send PR after merging PR #161 and fixing issue #129.

### PR DESCRIPTION
**Pull request by kimikage**
This fixes #163.

This PR also moves `real` and `reinterpret` to "conversions.jl", and removes the methods which were once needed due to ambiguity.

### CODE REVIEW

File: src/conversions.jl [hunk 1]
```diff
@@ -109,18 +109,20 @@ _convert(::Type{Cout}, ::Type{C1}, ::Type{C2}, c) where {Cout<:AbstractRGB,C1<:A
 _convert(::Type{A}, ::Type{C1}, ::Type{C2}, c, alpha=alpha(c)) where {A<:TransparentRGB,C1<:AbstractRGB,C2<:AbstractGray} = (g = convert(eltype(A), gray(c)); A(g, g, g, alpha))
 
 convert(::Type{RGB24},   x::Real) = RGB24(x, x, x)
-convert(::Type{ARGB32},  x::Real) = ARGB32(x, x, x, 1)
+convert(::Type{ARGB32},  x::Real) = ARGB32(x, x, x)
+convert(::Type{ARGB32},  x::Real, alpha) = ARGB32(x, x, x, alpha)
 convert(::Type{Gray24},  x::Real) = Gray24(x)
-convert(::Type{AGray32}, x::Real) = AGray32(x, 1)
+convert(::Type{AGray32}, x::Real) = AGray32(x)
```
Comment (kimikage) [inline src/conversions.jl]: Probably `AGray32(x, 1)` might be optimized by the compiler, but I think it is better that the alpha completion should be done by the constructors.

File: src/conversions.jl [hunk 2]
```diff
@@ -72,34 +72,24 @@ end
 convert(::Type{C}, c::C) where {C<:Colorant} = c
 convert(::Type{C}, c) where {C<:Colorant} = cconvert(ccolor(C, typeof(c)), c)
 cconvert(::Type{C}, c::C) where {C} = c
-cconvert(::Type{C}, c) where {C}    = _convert(C, base_color_type(C), base_color_type(c), c)
+cconvert(::Type{C}, c) where {C} = _convert(C, base_color_type(C), base_color_type(c), c)
+
 convert(::Type{C}, c::Color, alpha) where {C<:TransparentColor} = cconvert(ccolor(C, typeof(c)), c, alpha)
-cconvert(::Type{AlphaColor{C,T,N}}, c::C, alpha) where {C<:Color,T,N} = alphacolor(C)(c, alpha)
-cconvert(::Type{ColorAlpha{C,T,N}}, c::C, alpha) where {C<:Color,T,N} = coloralpha(C)(c, alpha)
```
Comment (kimikage) [inline src/conversions.jl]: `ccolor` should not return `AlphaColor`/`ColorAlpha` with the type of "instance" `c`, i.e. a concrete type.

File: src/conversions.jl [hunk 3]
```diff
@@ -72,34 +72,24 @@ end
...
 # Fallback definitions that print nice error messages
 _convert(::Type{C}, ::Any, ::Any, c) where {C} = error("No conversion of ", c, " to ", C, " has been defined")
 _convert(::Type{C}, C1::Any, C2::Any, c, alpha) where {C} = error("No conversion of (", c, ",alpha=$alpha) to ", C, " with consistency-types $C1 and $C2 has been defined")
 
 # Any AbstractRGB types can be interconverted
-# (the first 2 are just for ambiguity resolution)
-# Note: on julia 0.3 these have to be before the block below, or you
-# get a spurious ambiguity warning.
-_convert(::Type{Cout}, ::Type{C1}, ::Type{C1}, c) where {Cout<:AbstractRGB,C1<:AbstractRGB} = Cout(red(c), green(c), blue(c))
-_convert(::Type{A}, ::Type{C1}, ::Type{C1}, c) where {A<:TransparentRGB,C1<:AbstractRGB} = A(red(c), green(c), blue(c), alpha(c))
```
Comment (kimikage) [inline src/conversions.jl]: I don't exactly understand the reason, but it works without these now.
