### PR TITLE
[Alternative] Improve promotion rules (Fixes #129)

### LINKED ISSUE #129: Promotion rules for same base color pairs
As https://github.com/JuliaGraphics/Colors.jl/issues/273 shows, there are the problems with promotion rules for same base color pairs. Here is another simple example:
```julia
julia> promote_type(HSV{Float64}, HSV{Float32})
HSV

julia> promote(HSV{Float64}(0,0,0), HSV{Float32}(0,0,0))
ERROR: promotion of types HSV{Float64} and HSV{Float32} failed to change any arguments
Stacktrace:
 [1] error(::String, ::String, ::String) at .\error.jl:42
 [2] sametype_error(::Tuple{HSV{Float64},HSV{Float32}}) at .\promotion.jl:308
 [3] not_sametype(::Tuple{HSV{Float64},HSV{Float32}}, ::Tuple{HSV{Float64},HSV{Float32}}) at .\promotion.jl:302
 [4] promote(::HSV{Float64}, ::HSV{Float32}) at .\promotion.jl:285
 [5] top-level scope at REPL[2]:1
```

A simple (and tactless) solution is adding the rules [here](https://github.com/JuliaGraphics/ColorTypes.jl/blob/7ef745605d6a0897078712a0a7a156c51295b559/src/types.jl#L549-L579).
```julia
    @eval Base.promote_rule(::Type{$Csym{T1}}, ::Type{$Csym{T2}}) where {T1, T2} = $Csym{promote_type(T1, T2)}
    @eval Base.promote_rule(::Type{$acol{T1}}, ::Type{$acol{T2}}) where {T1, T2} = $acol{promote_type(T1, T2)}
    @eval Base.promote_rule(::Type{$cola{T1}}, ::Type{$cola{T2}}) where {T1, T2} = $cola{promote_type(T1, T2)}
```
Of course,
> RGB1 and RGB4 require special handling because of the alphadummy field

However, I don't know what should be returned by `promote_type(HSV, HSV{Float16})`.(`HSV{Float16}`? or `HSV{promote_type(eltype_default(HSV),Float16)}`?)

### PR DESCRIPTION
**Pull request by kimikage**
This PR is an alternative solution of PR #164.
The notable difference is that the rules implemented in this PR promote `AlphaColor` and `ColorAlpha` to `AlphaColor` instead of `TransparentColor`. (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/129#issuecomment-589990753)

### CODE REVIEW

File: test/conversions.jl [hunk 1]
```diff
@@ -114,29 +182,232 @@ end
...
+
 @testset "rgb conversions with abstract types" begin
     c = RGB(1, 0.6, 0)
     @test convert(Colorant, c) === RGB{Float64}(1, 0.6, 0)
     @test convert(Colorant{N0f8}, c) === RGB{N0f8}(1, 0.6, 0)
     @test convert(Colorant{Float32,3}, c) === RGB{Float32}(1, 0.6, 0)
     @test convert(Color, c) === RGB{Float64}(1, 0.6, 0)
     @test convert(Color{N0f8}, c) === RGB{N0f8}(1, 0.6, 0)
-    @test convert(Color{Float32}, c) === RGB{Float32}(1, 0.6, 0)
+    @test convert(Color{Float32,3}, c) === RGB{Float32}(1, 0.6, 0)
```
Comment (timholy) [inline test/conversions.jl]: Does it have trouble without the 3?

File: test/conversions.jl [hunk 2]
```diff
@@ -114,29 +182,232 @@ end
...
     @test convert(AbstractRGB, c) === RGB{Float64}(1, 0.6, 0)
     @test convert(AbstractRGB{N0f8}, c) === RGB{N0f8}(1, 0.6, 0)
     @test_throws ColorTypeResolutionError convert(TransparentColor, c)
     @test_throws ColorTypeResolutionError convert(TransparentColor{RGB{N0f8}}, c)
     @test_throws ColorTypeResolutionError convert(TransparentColor{RGB{N0f8},N0f8}, c)
-    @test_throws ColorTypeResolutionError convert(TransparentColor{RGB{N0f8},N0f8,2}, c)
+    @test_throws ColorTypeResolutionError convert(TransparentColor{RGB{N0f8},N0f8,4}, c)
```
Comment (timholy) [inline test/conversions.jl]: Good catch!

File: test/conversions.jl [hunk 3]
```diff
@@ -114,29 +182,232 @@ end
...
+    @test promote_type(Colorant, RGB{Float64}) == AlphaColor{C,T} where {T, C<:Color{T}}
+    @test promote_type(Colorant{N0f8}, RGB{Float64}) == AlphaColor{C,Float64} where {C<:Color{Float64}}
+    @test promote_type(Colorant{Float32,3}, RGB{Float64}) == AlphaColor{C,Float64,4} where C<:Color{Float64,3}
+    @test promote_type(Color, RGB{Float64}) === Color
+    @test promote_type(Color{N0f8}, RGB{Float64}) === Color{Float64}
+    @test promote_type(Color{Float32,3}, RGB{Float64}) === Color{Float64,3}
+    @test promote_type(AbstractRGB, RGB{Float64}) === RGB
+    @test promote_type(AbstractRGB{N0f8}, RGB{Float64}) === RGB{Float64}
+    @test promote_type(TransparentColor, RGB{Float64}) == AlphaColor{C,T} where {T, C<:Color{T}}
+    @test promote_type(TransparentColor{RGB{N0f8}}, RGB{Float64}) === ARGB
```
Comment (timholy) [inline test/conversions.jl]: Argh, this is indeed why it might be nice to have the `T` constrained to `eltype(C)`.

File: test/conversions.jl (hunk 1 above)
Comment (kimikage) [reply test/conversions.jl]: There is no trouble. However, `convert(Color{N0f8}, c)` and `convert(Color{Float32}, c)` are essentially the same case.

**Comment by kimikage** [comment]
Currently, PR #164 does not work well for promotions with abstract types. Although it is just because my heart broke off :tired_face:, it is true that this PR works better *at this time*.
It defeats the purpose of these promotion rules, but the users can explicitly convert color values or types. The users can also override the rules.

Therefore, I choose this!
